{% set name = "pygis" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygis-{{ version }}.tar.gz
  sha256: 0551d8bd2842c7a3eaf57cf9d5e7a79c76757a125ab78e5f81ed4428a3a09d32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - bokeh
    - datapane
    - geedim >=1.6.1
    - geemap >=0.18.1
    - geopandas
    - here-map-widget-for-jupyter
    - ipynb-py-convert
    - keplergl
    - leafmap >=0.14.0
    - localtileserver >=0.6.1
    - mapclassify >=2.4.0
    - netcdf4
    - osmnx
    - owslib
    - palettable
    - plotly
    - pydeck
    - python-mss
    - retry
    - rio-cogeo
    - rioxarray
    # - voila
    # - ipython >=7.34.0
    # - ipykernel >=6.15.1
    # - debugpy >=1.6.2
    # - ipygany
    # - ipyvtklink
    # - laspy
    # - panel
    # - pyntcloud
    # - pyvista

test:
  imports:
    - pygis
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/pygis
  summary: A Python package for installing optional dependencies for geemap and leafmap.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pygis.gishub.org
  dev_url: https://github.com/giswqs/pygis

extra:
  recipe-maintainers:
    - giswqs
