{% set name = "pygis" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygis-{{ version }}.tar.gz
  sha256: b0c2a94da823962c4a8f2bafed0cd08b955cecadedd8dac6bd925951650a417c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - bokeh
    - geedim >=1.6.1
    - geemap >=0.34.3
    - geopandas
    - ipynb-py-convert
    - keplergl
    - leafmap >=0.37.6
    - localtileserver >=0.10.0
    - mapclassify >=2.4.0
    - netcdf4
    - osmnx
    - overturemaps
    - owslib
    - palettable
    - plotly
    - python-mss
    - retry
    - rio-cogeo
    - rioxarray

    # - voila
    # - ipython >=7.34.0
    # - ipykernel >=6.15.1
    # - debugpy >=1.6.2
    # - ipygany
    # - ipyvtklink
    # - laspy
    # - panel
    # - pydeck
    # - pyntcloud
    # - pyvista

test:
  imports:
    - pygis
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/pygis
  summary: A Python package for installing optional dependencies for geemap and leafmap.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pygis.gishub.org
  dev_url: https://github.com/opengeos/pygis

extra:
  recipe-maintainers:
    - giswqs
