{% set name = "pygis" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygis-{{ version }}.tar.gz
  sha256: 31d07799be1e58be8f6728c35d877eec705df5bfe3f49188880d361a4e408109

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - gdal
    - geos
    - proj
    - pyproj
    - bash_kernel
    - python-duckdb
    - duckdb-engine
    - earthaccess
    - ffmpeg-python
    - fiona
    - geeadd
    - geedim
    - geemap
    - geopandas
    - hypercoast
    - ipykernel
    - jupysql
    - jupyter-server-proxy
    - laspy
    - python-kaleido
    - leafmap
    - mapclassify
    - maplibre
    - mapwidget
    - numpy
    - pandas
    - planetary-computer
    - pmtiles
    - pooch
    - py3dep
    - pyntcloud
    - pyvista
    - rasterio
    - rioxarray
    - shapely
    - solara
    - voila
    - voila_topbar
    - whiteboxgui
    - xarray
    - jupytext
    - mystmd
    - typst

test:
  imports:
    - pygis
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/pygis
  summary: A Python package for installing commonly used packages for GIS programming.
  description: A Python package for installing commonly used packages for GIS programming with only one command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pygis.gishub.org
  dev_url: https://github.com/opengeos/pygis

extra:
  recipe-maintainers:
    - giswqs
