{% set name = "pygis" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygis-{{ version }}.tar.gz
  sha256: e0a286c96d2957cdba2b077b0d5a5ac8d15d8ad01f95c5a24d2c06d65a2f4a41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - gdal
    - geos
    - proj
    - pyproj
    - python-duckdb
    - earthaccess
    - ffmpeg-python
    - fiona
    - geeadd
    - geedim
    - geemap
    - geopandas
    - hypercoast
    - ipykernel
    - jupyter-server-proxy
    - python-kaleido
    - leafmap
    - mapclassify
    - maplibre
    - mapwidget
    - numpy
    - pandas
    - planetary-computer
    - pmtiles
    - rasterio
    - rioxarray
    - shapely
    - solara
    - voila
    - voila_topbar
    - whiteboxgui
    - xarray

test:
  imports:
    - pygis
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/pygis
  summary: A Python package for installing commonly used packages for GIS programming.
  description: A Python package for installing commonly used packages for GIS programming with only one command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pygis.gishub.org
  dev_url: https://github.com/opengeos/pygis

extra:
  recipe-maintainers:
    - giswqs
